void OledPrintValue() {
  display.clearDisplay();
  display.setTextSize(1);
  display.setTextColor(WHITE);
  display.setCursor(0, 0);
  display.print("T:");
  (signSudut) ? display.print("-") : display.print("+");
  display.print(sudut);
  display.print(" (");
  display.print(gridX);
  display.print(",");
  display.print(gridY);
  display.println(")");
  display.print("X:");
  (signPosX) ? display.print("-") : display.print("+");
  display.println(posX);
  display.print("Y:");
  (signPosY) ? display.print("-") : display.print("+");
  display.print(posY);
  display.print("|");
  display.print(count);
  display.println();
  display.println();
  display.print(receiveddata[0]);
  display.print("|");
  display.print(receiveddata[1]);
  display.print("|");
  display.println(receiveddata[2]);
  display.print(receiveddata[3]);
  display.print("|");
  display.print(receiveddata[4]);
  display.print("|");
  display.println(receiveddata[5]);
  display.print(receiveddata[6]);
  display.print("|");
  display.print(receiveddata[7] << 8);
  display.print("|");
  display.println(receiveddata[8]);
  display.print(receiveddata[9]);
  display.print("|");
  display.print(receiveddata[10]);
  display.print("|");
  display.print(receiveddata[11]);
  display.print("|");
  display.println(receiveddata[12]);
  /*
  display.setCursor(84,0);
  display.print("M1:");
  display.println(int(rpmA));
  display.setCursor(84,8);
  display.print("M2:");
  display.println(int(rpmB));
  display.setCursor(84,16);  
  display.print("M3:");
  display.println(int(rpmC));
  display.setCursor(84,24);
  display.print("E1:");
  display.print(E);
  display.setCursor(84,32);
  display.print("E2:");
  display.print(valueEnc2);
  display.setCursor(84,40);
  display.print("E3:");
  display.print(valueEnc3); 
  display.setCursor(84,48);
  display.print("s:");
  display.print(digitalRead(PA0));
  display.setCursor(84,56);
  display.print(ButtonPress);
  display.print(" b:");
  display.println(!digitalRead(IRBola));
  */
  customKey = customKeypad.getKey();
  if (customKey != 0) ButtonPress = customKey;
  display.display();
}
